apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: mesh-demo
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: v1
  template:
    metadata:
      labels:
        app: client
        version: v1
    spec:
      serviceAccountName: client-sa
      containers:
      - name: client
        image: client_mesh:latest     # change if you push to a registry
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_PORT
          value: "8000"
        - name: TARGET_URL
          value: "http://service2.mesh-demo.svc.cluster.local:8000/echo"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: mesh-demo
  labels:
    app: client
spec:
  selector:
    app: client
    version: v1
  ports:
  - name: http
    port: 8000
    targetPort: 8000
