version: "3.8"

services:
  service2:
    build:
      context: .
      dockerfile: Dockerfile.api2
    ports:
      - "5001:5001"
    networks:
      - service_network

  locust:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --host=http://service2:5001
    ports:
      - "8089:8089"
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
