FROM python:3.9-slim

WORKDIR /app

COPY resource.py /app/
RUN pip install flask gunicorn

EXPOSE 5001

# Run Flask app via Gunicorn (4 worker processes)
CMD ["gunicorn", "--workers=4", "--threads=2", "--bind=0.0.0.0:5001", "resource:app"]
