apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: mesh-demo
  labels:
    app: resource
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource
      version: v1
  template:
    metadata:
      labels:
        app: resource
        version: v1
    spec:
      containers:
      - name: resource
        image: resource_mesh:latest   # change if you push to a registry
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: mesh-demo
  labels:
    app: resource
spec:
  selector:
    app: resource
    version: v1
  ports:
  - name: http
    port: 8000
    targetPort: 8000
